/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.sun.openpisces.TransformingPathConsumer2D;
import dao.ListaPersonas;
import entidades.Persona;
import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author Nico
 */
public class InterfazInfractor extends javax.swing.JFrame {

    public static ListaPersonas listapers;
    public static TablaInfractorModel tablainfractor;
    public static TablaMultaModel tablaMultas;

    int bandera, DNI = 0, bb=0;

//    imagenfondo fondo=new imagenfondo();
    /**
     * Creates new form InterfazInfractor
     */
    public InterfazInfractor() {
//        this.setContentPane(fondo);
        initComponents();
        this.setResizable(false);
        listapers = new ListaPersonas();
        tablainfractor = new TablaInfractorModel(listapers.getPersonaM());
        jTable1.setModel(tablainfractor);
        setLocationRelativeTo(null);
        inicioBotones();
        desactivartextfield();
        verTodos();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/iconovial.png")));
        JTextFieldBusqueda.setForeground(Color.gray);
    }

    public void inicioBotones() {
        Agregar.setEnabled(true);
        Eliminar.setEnabled(false);
        Modificar.setEnabled(false);
        Cancelar.setEnabled(false);
        Guardar.setEnabled(false);
        VerMultas.setEnabled(false);
    }

    public void verTodos() {
        listapers = new ListaPersonas(listapers.getPersonaM());
        jTable1.setModel(tablainfractor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoDNI = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new imagenfondo();
        jPanel2 = new javax.swing.JPanel();
        JTextFieldBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        VerTodos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        VerMultas = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        TextFieldApellido = new javax.swing.JTextField();
        TextFieldDNI = new javax.swing.JTextField();
        TextFieldEmail = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        DialogoDNI.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoDNI.setTitle("Error:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setText("El DNI que ingresaste, ya existe");

        jButton1.setActionCommand("Cerrar");
        jButton1.setLabel("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoDNILayout = new javax.swing.GroupLayout(DialogoDNI.getContentPane());
        DialogoDNI.getContentPane().setLayout(DialogoDNILayout);
        DialogoDNILayout.setHorizontalGroup(
            DialogoDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoDNILayout.setVerticalGroup(
            DialogoDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setAutoscrolls(true);
        jPanel1.setEnabled(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel2KeyTyped(evt);
            }
        });

        JTextFieldBusqueda.setText("Ingrese el DNI");
        JTextFieldBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextFieldBusquedaMouseClicked(evt);
            }
        });
        JTextFieldBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextFieldBusquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextFieldBusquedaKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarKeyPressed(evt);
            }
        });

        VerTodos.setText("Ver Todos");
        VerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Buscar)
                    .addComponent(VerTodos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Infractores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        VerMultas.setText("Ver Multas");
        VerMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerMultasActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VerMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Modificar)
                    .addComponent(Eliminar)
                    .addComponent(VerMultas))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");

        TextFieldNombre.setMaximumSize(new java.awt.Dimension(50, 50));
        TextFieldNombre.setNextFocusableComponent(TextFieldApellido);
        TextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNombreMouseClicked(evt);
            }
        });
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        TextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldNombreKeyTyped(evt);
            }
        });

        TextFieldApellido.setMaximumSize(new java.awt.Dimension(50, 50));
        TextFieldApellido.setNextFocusableComponent(TextFieldDNI);
        TextFieldApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldApellidoMouseClicked(evt);
            }
        });
        TextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldApellidoKeyTyped(evt);
            }
        });

        TextFieldDNI.setMaximumSize(new java.awt.Dimension(50, 50));
        TextFieldDNI.setName(""); // NOI18N
        TextFieldDNI.setNextFocusableComponent(TextFieldEmail);
        TextFieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldDNIMouseClicked(evt);
            }
        });
        TextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDNIActionPerformed(evt);
            }
        });
        TextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldDNIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldDNIKeyTyped(evt);
            }
        });

        TextFieldEmail.setMaximumSize(new java.awt.Dimension(50, 50));
        TextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldEmailMouseClicked(evt);
            }
        });
        TextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldEmailKeyTyped(evt);
            }
        });

        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(null);
        Guardar.setContentAreaFilled(false);
        Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setBackground(new java.awt.Color(0, 0, 0));
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancelar.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(null);
        Cancelar.setContentAreaFilled(false);
        Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel6))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel5)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(159, 159, 159))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(Cancelar)
                .addGap(260, 260, 260))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ListaPersonas getlistaPersonas() {
        return this.listapers;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void enviardatos() {
        if (!(TextFieldApellido.getText().equals("") || TextFieldDNI.getText().equals("")
                || TextFieldNombre.getText().equals("") || TextFieldEmail.getText().equals(""))) {
            switch (bandera) {
                case 1:
                    if (listapers.buscarPersonaMDNI(Integer.parseInt(TextFieldDNI.getText())) == false) {
                        listapers.guardar(new Persona(Integer.parseInt(TextFieldDNI.getText()),
                                TextFieldNombre.getText(),
                                TextFieldApellido.getText(),
                                TextFieldEmail.getText()));

                        tablainfractor.fireTableDataChanged();
                        JOptionPane.showMessageDialog(this, "Alta exitosa!", "Alta de Infractor", JOptionPane.INFORMATION_MESSAGE);
                        inicioBotones();
                        break;
                    } else {
                        JOptionPane.showMessageDialog(this, "El Dni que ingresaste ya existe", "Error:", JOptionPane.ERROR_MESSAGE);
                        inicioBotones();
                        limpiarDataTextField();
                        jTable1.setEnabled(true);
                        desactivartextfield();
                        break;
                    }
                case 2:
                    if (listapers.buscarPersonaMDNI(Integer.parseInt(TextFieldDNI.getText())) == false 
                            || DNI==Integer.parseInt(TextFieldDNI.getText())  ) {
                        activartextfield();
                        listapers.modificarPorDNI(DNI,
                                Integer.parseInt(TextFieldDNI.getText()),
                                TextFieldNombre.getText(),
                                TextFieldApellido.getText(),
                                TextFieldEmail.getText());
                        tablainfractor.fireTableDataChanged();
                        JOptionPane.showMessageDialog(this, "Modificacion exitosa!", "Modificar Infractor", JOptionPane.INFORMATION_MESSAGE);
                        inicioBotones();
                        limpiarDataTextField();
                        jTable1.setEnabled(true);
                        desactivartextfield();
                        actualizardatos();
                        break;
                    } else {
                        JOptionPane.showMessageDialog(this, "El Dni que ingresaste ya existe", "Error:", JOptionPane.ERROR_MESSAGE);
                        TextFieldDNI.requestFocus();
                        TextFieldDNI.selectAll();
                        break;
                    }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limpiarDataTextField() {
        TextFieldNombre.setText("");
        TextFieldApellido.setText("");
        TextFieldDNI.setText("");
        TextFieldEmail.setText("");
        JTextFieldBusqueda.setText("Ingrese el DNI");
        JTextFieldBusqueda.setForeground(Color.gray);
    }
    public static int getInfractorSeleccionado() {
        return jTable1.getSelectedRow();

    }
    private void VerMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerMultasActionPerformed
        abrirmultas();
//        jTable1.clearSelection();
    }//GEN-LAST:event_VerMultasActionPerformed

    public void abrirmultas() {
        Agregar.setEnabled(false);
        Eliminar.setEnabled(false);
        Modificar.setEnabled(false);
        Cancelar.setEnabled(true);
        Guardar.setEnabled(false);
        desactivartextfield();
        InterfazMultas interfazmultas = new InterfazMultas();
        interfazmultas.setTitle("Multas: " + TextFieldNombre.getText() + " " + TextFieldApellido.getText());
        interfazmultas.setVisible(true);
    }
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        bandera = 1;
        activarbotones();
        limpiarDataTextField();
    }//GEN-LAST:event_AgregarActionPerformed

    public void activartextfield() {
        TextFieldDNI.setEnabled(true);
        TextFieldEmail.setEnabled(true);
        TextFieldNombre.setEnabled(true);
        TextFieldApellido.setEnabled(true);
    }

    public void desactivartextfield() {
        TextFieldDNI.setEnabled(false);
        TextFieldEmail.setEnabled(false);
        TextFieldNombre.setEnabled(false);
        TextFieldApellido.setEnabled(false);
    }

    public void activarbotones() {
        Agregar.setEnabled(false);
        Eliminar.setEnabled(false);
        Modificar.setEnabled(false);
        Cancelar.setEnabled(true);
        Guardar.setEnabled(true);
        activartextfield();
    }

    private void VerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTodosActionPerformed
        actualizardatos();
    }//GEN-LAST:event_VerTodosActionPerformed

    public void actualizardatos(){
        tablainfractor = new TablaInfractorModel(listapers.getPersonaM());
        jTable1.setModel(tablainfractor);
        inicioBotones();
        tablainfractor.fireTableDataChanged();
        JTextFieldBusqueda.setText("Ingrese el DNI");
        JTextFieldBusqueda.setForeground(Color.gray);
        limpiarDataTextField();
    }
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (JTextFieldBusqueda.getText().equalsIgnoreCase("Ingrese el DNI") || JTextFieldBusqueda.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI para Buscar", "Error:", JOptionPane.ERROR_MESSAGE);
        } else {
            buscar();
            JTextFieldBusqueda.setText("Ingrese el DNI");
            JTextFieldBusqueda.setForeground(Color.gray);
        }


    }//GEN-LAST:event_BuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() == 2) {
            Agregar.setEnabled(false);
            Eliminar.setEnabled(false);
            Modificar.setEnabled(false);
            Cancelar.setEnabled(true);
            Guardar.setEnabled(false);
            desactivartextfield();
            InterfazMultas interfazmultas = new InterfazMultas();
            interfazmultas.setVisible(true);
        }
        desactivartextfield();
        JTable datosfila = (JTable) evt.getSource();
        //COPIO LOS DATOS DE LA SELECCION EN LOS TEXT FIELDS
        TextFieldDNI.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 0).toString());
        TextFieldNombre.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 1).toString());
        TextFieldApellido.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 2).toString());
        TextFieldEmail.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 3).toString());

        Agregar.setEnabled(false);
        Eliminar.setEnabled(true);
        Modificar.setEnabled(true);
        VerMultas.setEnabled(true);
        Cancelar.setEnabled(false);


    }//GEN-LAST:event_jTable1MouseClicked

    private void TextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDNIActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        bandera = 2;
        activarbotones();
        DNI = Integer.parseInt(TextFieldDNI.getText());
    }//GEN-LAST:event_ModificarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        cancelarboton();
    }//GEN-LAST:event_CancelarActionPerformed

    public void cancelarboton(){
        limpiarDataTextField();
        inicioBotones();
        limpiarDataTextField();
        desactivartextfield();
        jTable1.clearSelection();
    }
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        desactivartextfield();
        int accion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar?");
        if (accion == JOptionPane.YES_OPTION) {
            listapers.eliminarPorDNI(Integer.parseInt(TextFieldDNI.getText()));
            tablainfractor.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Se elimino con exito", "Eliminacion", JOptionPane.INFORMATION_MESSAGE);
            inicioBotones();
            limpiarDataTextField();
            desactivartextfield();
            actualizardatos();
        } else if (accion == JOptionPane.NO_OPTION) {

        } else if (accion == JOptionPane.CANCEL_OPTION) {
            limpiarDataTextField();
            inicioBotones();
            limpiarDataTextField();
            desactivartextfield();
            jTable1.clearSelection();
            actualizardatos();
        }

    }//GEN-LAST:event_EliminarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    public void buscar() {
        tablainfractor = new TablaInfractorModel(listapers.buscar(Integer.parseInt(JTextFieldBusqueda.getText())));
        if (tablainfractor.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Dni Inexistente", "Informacion:", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jTable1.setModel(tablainfractor);
            tablainfractor.fireTableDataChanged();
        }

    }
    private void BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyPressed
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        if (tecla == '\n') {
            buscar();
        }
    }//GEN-LAST:event_BuscarKeyPressed

    private void JTextFieldBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextFieldBusquedaMouseClicked
        if (evt.getClickCount() == 2) {
            JTextFieldBusqueda.setText("");
            JTextFieldBusqueda.setForeground(Color.black);
        }
        if (evt.getClickCount() == 1 && JTextFieldBusqueda.getText().equals("Ingrese el DNI")) {
            JTextFieldBusqueda.setText("");
            JTextFieldBusqueda.setForeground(Color.black);
        }
    }//GEN-LAST:event_JTextFieldBusquedaMouseClicked

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed

    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNombreKeyTyped
        char tecla = evt.getKeyChar();
//        if (!(Character.isLetter(evt.getKeyChar())) && tecla=='\b') evt.consume();
//        
        if (Character.isDigit(tecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldNombreKeyTyped

    private void TextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreKeyReleased

    private void TextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDNIKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
        if (TextFieldDNI.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldDNIKeyTyped

    private void TextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEmailKeyTyped

    private void JTextFieldBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextFieldBusquedaKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
        if (JTextFieldBusqueda.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_JTextFieldBusquedaKeyTyped

    private void TextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldApellidoKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldApellidoKeyTyped

    private void jPanel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2KeyTyped

    private void TextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNombreKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }

    }//GEN-LAST:event_TextFieldNombreKeyPressed

    private void JTextFieldBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextFieldBusquedaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_JTextFieldBusquedaKeyPressed

    private void TextFieldDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDNIKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldDNIKeyPressed

    private void TextFieldApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldApellidoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldApellidoKeyPressed

    private void TextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEmailKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldEmailKeyPressed

    private void TextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNombreMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldNombre.setText("");
        }
    }//GEN-LAST:event_TextFieldNombreMouseClicked

    private void TextFieldApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldApellidoMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldApellido.setText("");
        }
    }//GEN-LAST:event_TextFieldApellidoMouseClicked

    private void TextFieldDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldDNIMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldDNI.setText("");
        }
    }//GEN-LAST:event_TextFieldDNIMouseClicked

    private void TextFieldEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldEmailMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldEmail.setText("");
        }
    }//GEN-LAST:event_TextFieldEmailMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        cancelarboton();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        enviardatos();
    }//GEN-LAST:event_GuardarActionPerformed

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInfractor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInfractor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInfractor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInfractor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInfractor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JDialog DialogoDNI;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField JTextFieldBusqueda;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField TextFieldApellido;
    private javax.swing.JTextField TextFieldDNI;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JButton VerMultas;
    private javax.swing.JButton VerTodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    class imagenfondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/recursos/transito2.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
