/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dao.ListaPersonas;
import dao.ListaMultas;

import entidades.Multa;
import entidades.Persona;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Nico
 */
public class InterfazMultas extends javax.swing.JFrame {

    ListaMultas listamultas;
    ListaPersonas listapersonas;

    TablaMultaModel tablamulta;
    TablaInfractorModel tablainfractor;

    Persona personaSeleccionada;

    int bandera,ID=5;

    /**
     * Creates new form InterfazInfractor
     */
    public InterfazMultas() {
        initComponents();
        this.setResizable(false);
        personaSeleccionada = new Persona(
                InterfazInfractor.listapers.getPersonaSeleccionada(InterfazInfractor.getInfractorSeleccionado()));
        listamultas = new ListaMultas(personaSeleccionada.getMultas());
        tablamulta = new TablaMultaModel(personaSeleccionada.getMultas());
        jTableMultas.setModel(tablamulta);
        setLocationRelativeTo(null);
        tablamulta.fireTableDataChanged();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/iconovial.png")));
        NombreInfractor.setText(personaSeleccionada.getNombre() + " " + personaSeleccionada.getApellido());
        inicioBotones();
        desactivarTextField();
        actualizardetalles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new imagenfondo();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldAñoMulta = new javax.swing.JTextField();
        TextFieldDescripcionMulta = new javax.swing.JTextField();
        TextFieldPrecioMulta = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jComboBoxTipoDeMulta = new javax.swing.JComboBox<>();
        NombreInfractor = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Adeuda = new javax.swing.JTextField();
        cantMult = new javax.swing.JLabel();
        totalAdeudado = new javax.swing.JLabel();
        multasLeves = new javax.swing.JLabel();
        multasGraves = new javax.swing.JLabel();
        multasMuyGraves = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMultas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multas");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jComboBoxFiltrar.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Todos", "Leve", "Grave", "Muy Grave" }));
        jComboBoxFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Eliminar)
                    .addComponent(Modificar))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 187));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año");

        TextFieldAñoMulta.setNextFocusableComponent(TextFieldDescripcionMulta);
        TextFieldAñoMulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldAñoMultaMouseClicked(evt);
            }
        });
        TextFieldAñoMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAñoMultaActionPerformed(evt);
            }
        });
        TextFieldAñoMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldAñoMultaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldAñoMultaKeyTyped(evt);
            }
        });

        TextFieldDescripcionMulta.setNextFocusableComponent(TextFieldPrecioMulta);
        TextFieldDescripcionMulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldDescripcionMultaMouseClicked(evt);
            }
        });
        TextFieldDescripcionMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDescripcionMultaActionPerformed(evt);
            }
        });
        TextFieldDescripcionMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldDescripcionMultaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldDescripcionMultaKeyTyped(evt);
            }
        });

        TextFieldPrecioMulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldPrecioMultaMouseClicked(evt);
            }
        });
        TextFieldPrecioMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPrecioMultaActionPerformed(evt);
            }
        });
        TextFieldPrecioMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldPrecioMultaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldPrecioMultaKeyTyped(evt);
            }
        });

        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setToolTipText("");
        Guardar.setActionCommand("");
        Guardar.setBorder(null);
        Guardar.setContentAreaFilled(false);
        Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancelar.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(null);
        Cancelar.setContentAreaFilled(false);
        Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jComboBoxTipoDeMulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leve", "Grave", "Muy Grave" }));
        jComboBoxTipoDeMulta.setNextFocusableComponent(TextFieldAñoMulta);
        jComboBoxTipoDeMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeMultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDeMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(TextFieldAñoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(178, 178, 178))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(196, 196, 196))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldDescripcionMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldPrecioMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDeMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldDescripcionMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldAñoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldPrecioMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar)
                        .addGap(14, 14, 14))))
        );

        NombreInfractor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NombreInfractor.setForeground(new java.awt.Color(255, 255, 255));
        NombreInfractor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NombreInfractor.setText("Infractor");
        NombreInfractor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NombreInfractor.setFocusable(false);
        NombreInfractor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles Totales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad de Multas: ");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Adeudado: ");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cant. de Multas Leves:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cant. de Multas Graves: ");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cant. Multas Muy Graves:");

        Adeuda.setBackground(new java.awt.Color(240, 240, 240));
        Adeuda.setText("jTextField1");
        Adeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdeudaActionPerformed(evt);
            }
        });

        cantMult.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cantMult.setForeground(new java.awt.Color(255, 255, 255));
        cantMult.setText("0");

        totalAdeudado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalAdeudado.setForeground(new java.awt.Color(255, 255, 255));
        totalAdeudado.setText("0");
        totalAdeudado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        totalAdeudado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        multasLeves.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        multasLeves.setForeground(new java.awt.Color(255, 255, 255));
        multasLeves.setText("0");

        multasGraves.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        multasGraves.setForeground(new java.awt.Color(255, 255, 255));
        multasGraves.setText("0");

        multasMuyGraves.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        multasMuyGraves.setForeground(new java.awt.Color(255, 255, 255));
        multasMuyGraves.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(cantMult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel9))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(multasLeves, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalAdeudado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Adeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(multasGraves, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multasMuyGraves, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cantMult))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(multasLeves)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAdeudado)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Adeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multasGraves)
                            .addComponent(multasMuyGraves))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTableMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMultas.setOpaque(false);
        jTableMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMultas);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Infractor:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setFocusable(false);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(971, 971, 971))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMultasMouseClicked
        JTable datosfila = (JTable) evt.getSource();
        //COPIO LOS DATOS DE LA SELECCION EN LOS TEXT FIELDS
        //jComboBoxTipoDeMulta.set
        String id=datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 0).toString();
        ID=Integer.parseInt(id);
        jComboBoxTipoDeMulta.setSelectedItem(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 1).toString());
        TextFieldAñoMulta.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 2).toString());
        TextFieldDescripcionMulta.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 3).toString());
        TextFieldPrecioMulta.setText(datosfila.getModel().getValueAt(datosfila.getSelectedRow(), 4).toString());
        

        Agregar.setEnabled(false);
        Eliminar.setEnabled(true);
        Modificar.setEnabled(true);
        Cancelar.setEnabled(false);
        Guardar.setEnabled(false);
        desactivarTextField();
    }//GEN-LAST:event_jTableMultasMouseClicked

    private void AdeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdeudaActionPerformed

    private void jComboBoxTipoDeMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDeMultaActionPerformed
    public void cancelarboton(){
        inicioBotones();
        limpiarDataTextField();
        desactivarTextField();
        jTableMultas.clearSelection();
    }
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        cancelarboton();
    }//GEN-LAST:event_CancelarActionPerformed
    private void enviardatos() {
        if (Integer.parseInt(TextFieldAñoMulta.getText()) >= 1950 && Integer.parseInt(TextFieldAñoMulta.getText()) <= 2021) {
            if (!(((TextFieldAñoMulta.getText().equals(""))) || TextFieldDescripcionMulta.getText().equals("")
                    || TextFieldPrecioMulta.getText().equals(""))) {
                switch (bandera) {
                    case 1:
//                        ID=personaSeleccionada.getMultas().size();
                        ID=personaSeleccionada.getMultas().get(personaSeleccionada.getMultas().size()-1).getID() + 1 ;
                        Multa multa = new Multa(ID,Integer.parseInt(TextFieldAñoMulta.getText()),
                                Double.parseDouble(TextFieldPrecioMulta.getText()),
                                jComboBoxTipoDeMulta.getSelectedItem().toString(),
                                TextFieldDescripcionMulta.getText());
                        listamultas.guardar(multa);
                        tablamulta.fireTableDataChanged();
                        inicioBotones();
                        JOptionPane.showMessageDialog(this, "Nueva Multa Añadida!", "Nueva Multa", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case 2:
                        listamultas.modificarPorID(ID, new Multa(ID, Integer.parseInt(TextFieldAñoMulta.getText()),
                                Double.parseDouble(TextFieldPrecioMulta.getText()),
                                jComboBoxTipoDeMulta.getSelectedItem().toString(),
                                TextFieldDescripcionMulta.getText()));
                        tablamulta.fireTableDataChanged();
                        JOptionPane.showMessageDialog(this, "Modificacion exitosa!", "Modificar de alumno", JOptionPane.INFORMATION_MESSAGE);
                        inicioBotones();
                }
                actualizardetalles();
                desactivarTextField();
                limpiarDataTextField();
                actualizarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Faltan datos a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El año ingresado es incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        enviardatos();
    }//GEN-LAST:event_GuardarActionPerformed

    private void TextFieldAñoMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAñoMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAñoMultaActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int accion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar?");
        if (accion == JOptionPane.YES_OPTION) {
            listamultas.eliminarPorID(ID);
            tablamulta.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Se elimino con exito", "Eliminacion", JOptionPane.INFORMATION_MESSAGE);
            inicioBotones();
            limpiarDataTextField();
            desactivarTextField();
            actualizardetalles();
            actualizarDatos();
        } else if (accion == JOptionPane.NO_OPTION) {

        } else if (accion == JOptionPane.CANCEL_OPTION) {
            limpiarDataTextField();
            inicioBotones();
            limpiarDataTextField();
            desactivarTextField();
            jTableMultas.clearSelection();
            actualizarDatos();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        bandera = 2;
        activarguarcanc();
        activarTextField();
    }//GEN-LAST:event_ModificarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        bandera = 1;
        activarTextField();
        activarguarcanc();
    }//GEN-LAST:event_AgregarActionPerformed

    private void jComboBoxFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarActionPerformed
        buscar();
    }//GEN-LAST:event_jComboBoxFiltrarActionPerformed

    private void TextFieldPrecioMultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPrecioMultaKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car <= ',' || car > '.' || car == '-'))
            evt.consume();
    }//GEN-LAST:event_TextFieldPrecioMultaKeyTyped

    private void TextFieldAñoMultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldAñoMultaKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
        if (TextFieldAñoMulta.getText().length() >= 4)
            evt.consume();
    }//GEN-LAST:event_TextFieldAñoMultaKeyTyped

    private void TextFieldPrecioMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPrecioMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPrecioMultaActionPerformed

    private void TextFieldDescripcionMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDescripcionMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDescripcionMultaActionPerformed

    private void TextFieldDescripcionMultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDescripcionMultaKeyTyped
        char tecla = evt.getKeyChar();
        if (!(Character.isLetter(evt.getKeyChar())) && tecla == '\b') {
            evt.consume();
        }
//        
//        if (Character.isDigit(tecla)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_TextFieldDescripcionMultaKeyTyped

    private void TextFieldAñoMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldAñoMultaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldAñoMultaKeyPressed

    private void TextFieldDescripcionMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDescripcionMultaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldDescripcionMultaKeyPressed

    private void TextFieldPrecioMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPrecioMultaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            enviardatos();
        }
    }//GEN-LAST:event_TextFieldPrecioMultaKeyPressed

    private void TextFieldAñoMultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldAñoMultaMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldAñoMulta.setText("");
        }
    }//GEN-LAST:event_TextFieldAñoMultaMouseClicked

    private void TextFieldDescripcionMultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldDescripcionMultaMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldDescripcionMulta.setText("");
        }
    }//GEN-LAST:event_TextFieldDescripcionMultaMouseClicked

    private void TextFieldPrecioMultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldPrecioMultaMouseClicked
        if (evt.getClickCount() == 2) {
            TextFieldPrecioMulta.setText("");
        }
    }//GEN-LAST:event_TextFieldPrecioMultaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        cancelarboton();
    }//GEN-LAST:event_jPanel1MouseClicked

    public void inicioBotones() {
        Agregar.setEnabled(true);
        Guardar.setEnabled(false);
        Modificar.setEnabled(false);
        Eliminar.setEnabled(false);
        Cancelar.setEnabled(false);
    }

    public void desactivarTextField() {
        jComboBoxTipoDeMulta.setEnabled(false);
        TextFieldAñoMulta.setEnabled(false);
        TextFieldDescripcionMulta.setEnabled(false);
        TextFieldPrecioMulta.setEnabled(false);
    }

    public void activarTextField() {
        jComboBoxTipoDeMulta.setEnabled(true);
        TextFieldAñoMulta.setEnabled(true);
        TextFieldDescripcionMulta.setEnabled(true);
        TextFieldPrecioMulta.setEnabled(true);
    }

    private void limpiarDataTextField() {
        jComboBoxTipoDeMulta.setSelectedItem("Leve");
        TextFieldAñoMulta.setText("");
        TextFieldDescripcionMulta.setText("");
        TextFieldPrecioMulta.setText("");
    }

    public void activarguarcanc() {
        Agregar.setEnabled(false);
        Guardar.setEnabled(true);
        Modificar.setEnabled(false);
        Eliminar.setEnabled(false);
        Cancelar.setEnabled(true);
    }

    public void actualizarDatos() {
        jComboBoxFiltrar.setSelectedItem("Ver Todos");
        buscar();
    }

    public void buscar() {
        String combobox1 = jComboBoxFiltrar.getSelectedItem().toString();
        if (combobox1 != "Ver Todos") {
            tablamulta = new TablaMultaModel(listamultas.buscar(jComboBoxFiltrar.getSelectedItem().toString()));
        } else {
            tablamulta = new TablaMultaModel(personaSeleccionada.getMultas());
        }
        jTableMultas.setModel(tablamulta);
        tablamulta.fireTableDataChanged();
    }

    public void actualizardetalles() {
        cantMult.setText(Integer.toString(personaSeleccionada.cantidadMultas()));
        multasLeves.setText(Integer.toString(personaSeleccionada.multasLeves()));
        multasGraves.setText(Integer.toString(personaSeleccionada.multasGraves()));
        multasMuyGraves.setText(Integer.toString(personaSeleccionada.multasMuyGraves()));
        totalAdeudado.setText(Double.toString(personaSeleccionada.TotalMonto()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adeuda;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel NombreInfractor;
    private javax.swing.JTextField TextFieldAñoMulta;
    private javax.swing.JTextField TextFieldDescripcionMulta;
    private javax.swing.JTextField TextFieldPrecioMulta;
    private javax.swing.JLabel cantMult;
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JComboBox<String> jComboBoxTipoDeMulta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMultas;
    private javax.swing.JLabel multasGraves;
    private javax.swing.JLabel multasLeves;
    private javax.swing.JLabel multasMuyGraves;
    private javax.swing.JLabel totalAdeudado;
    // End of variables declaration//GEN-END:variables
    class imagenfondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/recursos/transito2.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
